<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>dgVoodoo2 Easy Installer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DgVoodooEasyInstaller.Core\DgVoodooEasyInstaller.Core.csproj" />
  </ItemGroup>
</Project>
